import {
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

import { fakeTrust, type FakeTrust } from '../../test/doubles/trust.js';
import { fakeHost, type FakeHost } from '../../test/doubles/watchHost.js';
import {
  WorkflowIRSchema,
  validateWorkflow,
  type WorkflowIR,
} from '../core/rules.js';
import { messages } from '../messages.js';
import type { Problem } from '../problem.js';
import { QUEUE_SDK } from '../runs/sdk.js';
import type { StatusBar } from '../statusBar.js';
import {
  makeProject,
  readWorkflowFixture,
  writeWorkflow,
} from '../test-support/project.js';

import { generate, type CodegenResult } from './codegen.js';
import {
  LIB_GLOB,
  PROPOSAL_GLOB,
  WORKFLOW_GLOB,
  watchProjects,
  type Watchers,
} from './index.js';
import { scanProject } from './manifest.js';

/**
 * The loop between saving a workflow and having
 * code for it.
 *
 * Two halves, and they fail in different ways. The
 * generation itself is answerable against the
 * files on disk: the code is there, it carries the
 * header that says nobody may edit it, and what
 * the rules found about the document is reported
 * at the severity the rule fixed rather than at
 * whatever the reporting code felt like. The
 * wiring is answerable only by driving it — a
 * watcher registered on the wrong glob, or on a
 * folder nobody trusted, does nothing at all and
 * says nothing about it.
 */

const HEADER = '// GENERATED BY MBOSS — DO NOT EDIT.';

/** What the status bar was told, in order. */
type Reported = StatusBar & { finished: { ms: number; ok: boolean }[] };

function reporter(): Reported {
  const finished: { ms: number; ok: boolean }[] = [];

  return {
    finished,
    codegenFinished: (ms, ok) => void finished.push({ ms, ok }),
    codegenNeedsTrust: () => {},
    dispose: () => {},
  };
}

/**
 * Waits for something to become true rather than
 * for a length of time. Reading a project's
 * code-behind is real work and how long it takes is
 * not this spec's business.
 */
async function until(ready: () => boolean): Promise<void> {
  for (let tries = 0; tries < 600 && !ready(); tries += 1) {
    await new Promise((resolve) => setTimeout(resolve, 25));
  }

  expect(ready()).toBe(true);
}

/** Long enough for anything still in flight. Only
 *  used to assert that nothing more happens. */
async function quiet(): Promise<void> {
  await new Promise((resolve) => setTimeout(resolve, 200));
}

/** Every generated file, by project-relative
 *  path. */
function generatedFiles(project: string): string[] {
  const dir = join(project, 'src', 'workflows');

  return readdirSync(dir)
    .sort()
    .map((name) => `src/workflows/${name}`);
}

/** The problems reported against one file. */
function about(result: CodegenResult, path: string): Problem[] {
  return result.problems.filter((problem) => problem.file === path);
}

describe('generating from a document that compiles', () => {
  it('writes the code, with the header that says who owns it', async () => {
    const project = await makeProject({ lib: 'lib' });
    writeWorkflow(project, 'groom_booking');

    const result = await generate(project);

    const generated = readFileSync(
      join(project, 'src', 'workflows', 'groom_booking.workflow.ts'),
      'utf8',
    );

    expect(result.ok).toBe(true);
    expect(generated.split('\n')[0]).toBe(HEADER);
  });

  it('reports exactly what it put on disk', async () => {
    const project = await makeProject({ lib: 'lib' });
    writeWorkflow(project, 'groom_booking');

    const result = await generate(project);

    expect([...result.written].sort()).toEqual(generatedFiles(project));
  });

  it('says how long it took', async () => {
    const project = await makeProject({ lib: 'lib' });
    writeWorkflow(project, 'groom_booking');

    expect((await generate(project)).ms).toBeGreaterThanOrEqual(0);
  });
});

describe('what the rules found', () => {
  /**
   * Computed by asking the same function the canvas
   * and the compiler ask, rather than written out
   * here: a copy of core's wording in this file
   * would drift from core's wording without
   * anything failing.
   */
  it('is reported unchanged, against the document it is about', async () => {
    const project = await makeProject({ lib: 'lib' });
    const path = writeWorkflow(project, 'groom_booking');
    const ir = WorkflowIRSchema.parse(JSON.parse(readFileSync(path, 'utf8')));

    const result = await generate(project);
    const expected = validateWorkflow(ir, {
      manifest: scanProject(project).manifest,
    });

    expect(about(result, path)).toEqual(
      expected.map((found) => ({
        file: path,
        code: found.code,
        severity: found.severity,
        message: found.message,
      })),
    );
  });

  /**
   * The three rules about work not done yet report
   * as warnings, and every other rule as an error.
   * A pipeline that flattened them would turn every
   * half-drawn draft into a wall of red.
   */
  it('keeps a warning a warning and an error an error', async () => {
    const project = await makeProject({ lib: 'lib' });
    const path = writeMixed(project);

    const found = about(await generate(project), path);

    expect(found.filter((one) => one.severity === 'warning')).not.toHaveLength(
      0,
    );
    expect(found.filter((one) => one.severity === 'error')).not.toHaveLength(0);
  });

  it('names the rule, so a reader can look it up', async () => {
    const project = await makeProject();
    const path = writeWorkflow(project, 'empty_draft');

    expect(about(await generate(project), path)).toEqual([
      expect.objectContaining({ code: 'V01', severity: 'warning' }),
    ]);
  });
});

describe('a document that will not parse', () => {
  /**
   * The ordinary state of a file somebody is typing
   * into, and of one an agent is halfway through
   * writing. Throwing here would take the whole
   * project's generation down over one file.
   */
  it('is reported rather than thrown', async () => {
    const project = await makeProject({ lib: 'lib' });
    writeWorkflow(project, 'groom_booking');
    const broken = join(
      project,
      '.mboss',
      'workflows',
      'half_typed.workflow.json',
    );
    writeFileSync(broken, '{ "nodes": [', 'utf8');

    const result = await generate(project);

    expect(result.ok).toBe(false);
    expect(about(result, broken)).toHaveLength(1);
    expect(about(result, broken)[0]?.severity).toBe('error');
  });

  it('leaves the code that was already generated alone', async () => {
    const project = await makeProject({ lib: 'lib' });
    writeWorkflow(project, 'groom_booking');
    await generate(project);

    writeFileSync(
      join(project, '.mboss', 'workflows', 'half_typed.workflow.json'),
      '{ "nodes": [',
      'utf8',
    );
    await generate(project);

    expect(generatedFiles(project)).toContain(
      'src/workflows/groom_booking.workflow.ts',
    );
  });
});

/**
 * The compiler refuses a project all or nothing, so
 * one bad document costs every other document its
 * generated code. Until now the panel said only
 * what was wrong with the bad one, and a person
 * looking at a workflow that had simply stopped
 * being regenerated had nothing at all to read.
 */
describe('what a refusal costs the documents beside it', () => {
  it('says which document was not regenerated, and which refused it', async () => {
    const project = await makeProject({ lib: 'lib' });
    const good = writeWorkflow(project, 'groom_booking');
    writeMixed(project);

    const result = await generate(project);

    expect(result.ok).toBe(false);
    expect(result.written).toEqual([]);

    const errors = about(result, good).filter(
      (problem) => problem.severity === 'error',
    );

    expect(errors).toEqual([
      {
        file: good,
        message: messages.codegenNotRegenerated('groom_booking', 'mixed'),
        severity: 'error',
      },
    ]);
  });

  /**
   * One name, not a list. A sentence naming three
   * documents stops being read, and any one of them
   * is enough of a thread to pull — each carries its
   * own errors in the same panel.
   */
  it('names one refusal when several documents refuse at once', async () => {
    const project = await makeProject({ lib: 'lib' });
    const good = writeWorkflow(project, 'groom_booking');
    writeMixed(project, 'mixed_one');
    writeMixed(project, 'mixed_two');

    const result = await generate(project);
    const said = about(result, good).filter(
      (problem) => problem.severity === 'error',
    );

    expect(said).toHaveLength(1);
    expect([
      messages.codegenNotRegenerated('groom_booking', 'mixed_one'),
      messages.codegenNotRegenerated('groom_booking', 'mixed_two'),
    ]).toContain(said[0]?.message);
  });

  /**
   * Nothing clears this: the problem sink replaces
   * the whole set on every publish, so a diagnostic
   * that is no longer computed is a diagnostic that
   * is no longer shown.
   */
  it('says nothing once the refused document compiles', async () => {
    const project = await makeProject({ lib: 'lib' });
    const good = writeWorkflow(project, 'groom_booking');
    const refused = writeMixed(project);

    await generate(project);
    rmSync(refused);

    const result = await generate(project);

    expect(result.ok).toBe(true);
    expect(
      about(result, good).filter((problem) => problem.severity === 'error'),
    ).toEqual([]);
  });
});

/**
 * A queue runs only if the app registers it at
 * boot, and the boot is the person's file: mBoss
 * writes `src/app/main.ts` when it creates a
 * project and never touches it again. So a project
 * made before queues existed compiles a queue into
 * code that nothing ever starts, and the rows it
 * enqueues wait for ever with nothing anywhere
 * saying why.
 */
describe('a project whose boot never registers its queues', () => {
  it('names the two lines to add, on the file they go in', async () => {
    const project = await makeProject({ lib: 'lib' });
    writeWorkflow(project, 'queue_partitioned');
    const main = olderBoot(project);

    const said = about(await generate(project), main);

    expect(said).toHaveLength(1);
    expect(said[0]?.severity).toBe('error');
    expect(said[0]?.message).toContain(
      "import { registerQueues } from './queues.js';",
    );
    expect(said[0]?.message).toContain('await registerQueues(queues);');
    expect(said[0]?.message).toContain('DBOS.launch()');
  });

  /** Said, not done. The file belongs to whoever
   *  is working in the project. */
  it('leaves the file it is about exactly as it was', async () => {
    const project = await makeProject({ lib: 'lib' });
    writeWorkflow(project, 'queue_partitioned');
    const main = olderBoot(project);
    const before = readFileSync(main, 'utf8');

    await generate(project);

    expect(readFileSync(main, 'utf8')).toBe(before);
  });

  /**
   * Which is also how it clears. It is computed
   * afresh on every generation and the problem
   * sink replaces the whole set, so one that stops
   * being computed stops being shown.
   */
  it('says nothing about a boot that registers them', async () => {
    const project = await makeProject({ lib: 'lib' });
    writeWorkflow(project, 'queue_partitioned');

    expect(about(await generate(project), mainFile(project))).toEqual([]);
  });

  it('says nothing about a project with no queue in it', async () => {
    const project = await makeProject({ lib: 'lib' });
    writeWorkflow(project, 'groom_booking');
    const main = olderBoot(project);

    expect(about(await generate(project), main)).toEqual([]);
  });
});

/**
 * The other half of the same setup. A queue block
 * compiles to enqueue options that older clients
 * have no fields for, so a project pinned below
 * the floor gets code it cannot run — and the
 * lockfile the extension already reads is enough
 * to say so.
 */
describe('a project pinned to an SDK too old for a queue', () => {
  it('names the floor and what the project is locked at', async () => {
    const project = await makeProject({ lib: 'lib' });
    writeWorkflow(project, 'queue_partitioned');
    lockedAt(project, '4.25.14');

    const said = about(await generate(project), manifestFile(project));

    expect(said).toEqual([
      {
        file: manifestFile(project),
        message: messages.codegenQueuesNeedSdk('4.25.14'),
        severity: 'error',
      },
    ]);

    // The sentence carries the floor as a literal,
    // and the check compares against the constant.
    expect(said[0]?.message).toContain(QUEUE_SDK);
  });

  it('says nothing about a project already at the floor', async () => {
    const project = await makeProject({ lib: 'lib' });
    writeWorkflow(project, 'queue_partitioned');
    lockedAt(project, QUEUE_SDK);

    expect(about(await generate(project), manifestFile(project))).toEqual([]);
  });

  /** Two ordinary states of a folder somebody is
   *  working in, and neither of them is an answer
   *  about a version. */
  it('says nothing when the lockfile never names the SDK', async () => {
    const project = await makeProject({ lib: 'lib' });
    writeWorkflow(project, 'queue_partitioned');
    lockedWithoutSdk(project);

    expect(about(await generate(project), manifestFile(project))).toEqual([]);
  });

  it('says nothing when there is no lockfile', async () => {
    const project = await makeProject({ lib: 'lib' });
    writeWorkflow(project, 'queue_partitioned');

    expect(about(await generate(project), manifestFile(project))).toEqual([]);
  });

  it('says nothing about a project with no queue in it', async () => {
    const project = await makeProject({ lib: 'lib' });
    writeWorkflow(project, 'groom_booking');
    lockedAt(project, '4.25.14');

    expect(about(await generate(project), manifestFile(project))).toEqual([]);
  });
});

describe('code-behind that does not compile', () => {
  it('is reported against the file that does not', async () => {
    const project = await makeProject({ lib: 'lib-broken' });
    writeWorkflow(project, 'empty_draft');

    const result = await generate(project);
    const path = join(project, 'lib', 'broken.ts');

    expect(about(result, path)).not.toHaveLength(0);
  });
});

describe('a compile that fails for a reason nobody chose', () => {
  /**
   * Not something a person could have typed — here,
   * a directory the compiler has to write into that
   * is not a directory. Reported all the same,
   * because a status bar that never updates and a
   * panel that never fills reads as the extension
   * having stopped working for no reason.
   */
  it('is reported rather than left silent', async () => {
    const project = await makeProject({ lib: 'lib' });
    writeWorkflow(project, 'groom_booking');

    rmSync(join(project, 'src'), { recursive: true });
    writeFileSync(join(project, 'src'), '', 'utf8');

    const result = await generate(project);

    expect(result.ok).toBe(false);
    expect(about(result, join(project, '.mboss'))).toEqual([
      expect.objectContaining({ severity: 'error' }),
    ]);
  });
});

describe('a project that is not one', () => {
  it('generates nothing and says nothing', async () => {
    const project = await makeProject();
    const result = await generate(join(project, 'not-a-project'));

    expect(result.ok).toBe(false);
    expect(result.written).toEqual([]);
  });
});

describe('the watchers', () => {
  it('watch the three things a project changes through', async () => {
    const { host } = await watching();

    expect(host.watching.map((one) => one.glob).sort()).toEqual(
      [LIB_GLOB, PROPOSAL_GLOB, WORKFLOW_GLOB].sort(),
    );
  });

  it('regenerate when a workflow document changes', async () => {
    const { project, host, status } = await watching({ lib: 'lib' });
    writeWorkflow(project, 'groom_booking');

    host.fire(WORKFLOW_GLOB, join(project, '.mboss', 'workflows', 'x.json'));

    await until(() => status.finished.length === 1);
    expect(generatedFiles(project)).toContain(
      'src/workflows/groom_booking.workflow.ts',
    );
  });

  it('regenerate when a document is saved in the editor', async () => {
    const { project, host, status } = await watching({ lib: 'lib' });
    writeWorkflow(project, 'groom_booking');

    host.save(
      join(project, '.mboss', 'workflows', 'groom_booking.workflow.json'),
    );

    await until(() => status.finished.length === 1);
    expect(generatedFiles(project)).toContain(
      'src/workflows/groom_booking.workflow.ts',
    );
  });

  it('ignore a save of a file that is not a workflow', async () => {
    const { project, host, status } = await watching({ lib: 'lib' });

    host.save(join(project, 'lib', 'notes.md'));

    await quiet();
    expect(status.finished).toHaveLength(0);
  });

  it('regenerate when the code-behind changes', async () => {
    const { project, host, status } = await watching({ lib: 'lib' });
    writeWorkflow(project, 'groom_booking');

    host.fire(LIB_GLOB, join(project, 'lib', 'findSlot.ts'));

    await until(() => status.finished.length === 1);
  });

  it('cost one generation for a burst of events', async () => {
    const { project, host, status } = await watching({ lib: 'lib' });
    writeWorkflow(project, 'groom_booking');
    const path = join(project, '.mboss', 'workflows', 'x.json');

    for (let event = 0; event < 5; event += 1) host.fire(WORKFLOW_GLOB, path);

    await until(() => status.finished.length === 1);
    await quiet();

    expect(status.finished).toHaveLength(1);
  });

  /**
   * A document a generation has already read is
   * nothing to answer: the code reflects those bytes.
   * That is what makes an approval, an undo and the
   * canvas's own write cost one generation rather
   * than two — the write, and then the event about
   * it.
   */
  it('answer an event about a document they have generated from with nothing', async () => {
    const { project, host, status, watchers } = await watching({ lib: 'lib' });
    const path = writeWorkflow(project, 'groom_booking');

    await watchers.generateNow();
    host.fire(WORKFLOW_GLOB, path);
    await quiet();

    expect(status.finished).toHaveLength(1);
  });

  /** The editor's watcher can deliver the event
   *  before the generation that reads the document
   *  has accounted for it, so the question is asked
   *  again when the debounced run fires. */
  it('answer it with nothing even when the event arrives first', async () => {
    const { project, host, status, watchers } = await watching({ lib: 'lib' });
    const path = writeWorkflow(project, 'groom_booking');

    host.fire(WORKFLOW_GLOB, path);
    await watchers.generateNow();
    await quiet();

    expect(status.finished).toHaveLength(1);
  });

  it('still answer a document that changed since', async () => {
    const { project, host, status, watchers } = await watching({ lib: 'lib' });
    const path = writeWorkflow(project, 'groom_booking');

    await watchers.generateNow();
    writeFileSync(path, readWorkflowFixture('empty_draft'), 'utf8');
    host.fire(WORKFLOW_GLOB, path);

    await until(() => status.finished.length === 2);
  });

  it('publish what they found where a person will see it', async () => {
    const { project, host } = await watching();
    const path = writeWorkflow(project, 'empty_draft');

    host.fire(WORKFLOW_GLOB, path);

    await until(() => host.published.length > 0);
    expect(host.published.at(-1)).toEqual([
      expect.objectContaining({ file: path, code: 'V01' }),
    ]);
  });

  it('tell the status bar what the generation cost', async () => {
    const { project, host, status } = await watching({ lib: 'lib' });
    writeWorkflow(project, 'groom_booking');

    host.fire(WORKFLOW_GLOB, join(project, '.mboss', 'workflows', 'x.json'));

    await until(() => status.finished.length === 1);
    expect(status.finished[0]?.ok).toBe(true);
    expect(status.finished[0]?.ms).toBeGreaterThanOrEqual(0);
  });

  /**
   * Said out loud, because a generation is also the
   * moment a project's code-behind was last read —
   * and an open canvas draws its palette, its picker
   * and its typed wiring from that.
   */
  it('say which project has been generated', async () => {
    const { project, host, watchers } = await watching({ lib: 'lib' });
    writeWorkflow(project, 'groom_booking');
    const seen: string[] = [];
    watchers.onGenerated((one) => void seen.push(one));

    host.fire(LIB_GLOB, join(project, 'lib', 'findSlot.ts'));

    await until(() => seen.length === 1);
    expect(seen).toEqual([project]);
  });

  it('notice a proposal arriving', async () => {
    const { project, host, watchers } = await watching();
    const seen: string[] = [];
    watchers.onProposal((path) => void seen.push(path));

    const path = join(project, '.mboss', 'proposals', 'p1.json');
    host.fire(PROPOSAL_GLOB, path);

    expect(seen).toEqual([path]);
  });

  it('let go of the PROBLEMS they published when disposed', async () => {
    const { host, watchers } = await watching();

    watchers.dispose();

    expect(host.disposed).toBe(true);
  });
});

describe('a folder nobody has trusted', () => {
  /**
   * Generating code writes TypeScript into the
   * folder, which is exactly what workspace trust
   * is a decision about. The canvas still draws and
   * still shows what the rules found; nothing runs
   * and nothing is written.
   */
  it('generates nothing', async () => {
    const { project, host, status } = await watching({
      lib: 'lib',
      trusted: false,
    });
    writeWorkflow(project, 'groom_booking');

    host.fire(WORKFLOW_GLOB, join(project, '.mboss', 'workflows', 'x.json'));

    await quiet();
    expect(status.finished).toHaveLength(0);
  });

  it('starts the moment it is trusted', async () => {
    const { project, trust, status } = await watching({
      lib: 'lib',
      trusted: false,
    });
    writeWorkflow(project, 'groom_booking');

    trust.grant();

    await until(() => status.finished.length === 1);
    expect(generatedFiles(project)).toContain(
      'src/workflows/groom_booking.workflow.ts',
    );
  });

  it('says on the status bar why nothing is happening', async () => {
    let asked = 0;
    const status: Reported = {
      ...reporter(),
      codegenNeedsTrust: () => void (asked += 1),
    };
    const project = await makeProject();
    const host = fakeHost({ folders: [project] });

    watchProjects(host, fakeTrust(false), status, { debounceMs: 5 }).dispose();

    expect(asked).toBe(1);
  });
});

describe('generating on demand', () => {
  it('does the work whatever the watchers were waiting for', async () => {
    const { project, watchers } = await watching({ lib: 'lib' });
    writeWorkflow(project, 'groom_booking');

    const run = await watchers.generateNow();

    expect(run).toMatchObject({ ran: true, ok: true, ms: expect.any(Number) });
    expect(generatedFiles(project)).toContain(
      'src/workflows/groom_booking.workflow.ts',
    );
  });

  /** Handed back as well as published, because the
   *  caller that asked for this generation may be
   *  the one that caused what it found. */
  it('hands back what it found', async () => {
    const { project, watchers } = await watching({ lib: 'lib-broken' });
    writeWorkflow(project, 'empty_draft');

    const run = await watchers.generateNow();

    expect(run.ran && run.problems).toContainEqual(
      expect.objectContaining({ file: join(project, 'lib', 'broken.ts') }),
    );
  });

  it('says it cannot when the folder is not trusted', async () => {
    const { watchers } = await watching({ trusted: false });

    expect(await watchers.generateNow()).toEqual({
      ran: false,
      reason: 'untrusted',
    });
  });

  it('says it cannot when no folder here is a project', async () => {
    const status = reporter();
    const host = fakeHost({ folders: ['/nowhere/at/all'] });
    const watchers = watchProjects(host, fakeTrust(), status, {
      debounceMs: 5,
    });

    expect(await watchers.generateNow()).toEqual({
      ran: false,
      reason: 'noProject',
    });

    watchers.dispose();
  });
});

/**
 * A watched project and the doubles it is watched
 * through. The window is short because these specs
 * wait on what happened, not on the clock.
 */
async function watching(opts?: {
  lib?: 'lib' | 'lib-broken';
  trusted?: boolean;
}): Promise<{
  project: string;
  host: FakeHost;
  trust: FakeTrust;
  status: Reported;
  watchers: Watchers;
}> {
  const project = await makeProject(
    opts?.lib === undefined ? undefined : { lib: opts.lib },
  );
  const host = fakeHost({ folders: [project] });
  const trust = fakeTrust(opts?.trusted ?? true);
  const status = reporter();
  const watchers = watchProjects(host, trust, status, { debounceMs: 5 });

  return { project, host, trust, status, watchers };
}

/**
 * A document with one of each severity: two blocks
 * wired with types that do not meet, and no trigger
 * to start any of it.
 */
function writeMixed(project: string, name = 'mixed'): string {
  const document = JSON.parse(
    readWorkflowFixture('groom_booking'),
  ) as WorkflowIR;
  const ir = {
    ...document,
    name,
    title: 'Mixed',
    nodes: document.nodes.filter((node) =>
      ['parse_request', 'find_slot'].includes(node.id),
    ),
    edges: document.edges
      .filter((edge) => edge.id === 'e2')
      .map((edge) => ({ ...edge, type: 'WebhookEvent' })),
  };

  const path = join(project, '.mboss', 'workflows', `${name}.workflow.json`);

  mkdirSync(join(project, '.mboss', 'workflows'), { recursive: true });
  writeFileSync(path, `${JSON.stringify(ir, null, 2)}\n`, 'utf8');

  return path;
}

/** The boot file mBoss writes once, when it
 *  creates a project. */
function mainFile(project: string): string {
  return join(project, 'src', 'app', 'main.ts');
}

/** Where a person edits the range their project
 *  installs by. */
function manifestFile(project: string): string {
  return join(project, 'package.json');
}

/**
 * The same boot as it was written before queues
 * existed: no import, no call, and no `queues`
 * among what it takes from the registry.
 *
 * Scaffolding an old project is not on offer, so
 * the current one is unwound. The assertion is
 * what keeps that honest — a rewording upstream
 * would otherwise leave this a no-op and the cases
 * that use it passing for the wrong reason.
 */
function olderBoot(project: string): string {
  const path = mainFile(project);
  const older = readFileSync(path, 'utf8')
    .replace("import { registerQueues } from './queues.js';\n", '')
    .replace('  await registerQueues(queues);\n', '')
    .replace(
      'import { queues, schedules, workflows }',
      'import { schedules, workflows }',
    );

  expect(older).not.toContain('registerQueues');
  writeFileSync(path, older, 'utf8');

  return path;
}

/** A lockfile pinning the SDK the way `npm ci`
 *  would have. */
function lockedAt(project: string, version: string): void {
  writeLock(project, {
    name: 'fixture_app',
    lockfileVersion: 3,
    packages: {
      '': { name: 'fixture_app' },
      'node_modules/@dbos-inc/dbos-sdk': { version },
    },
  });
}

/** A lockfile of a project that never installed
 *  the SDK. */
function lockedWithoutSdk(project: string): void {
  writeLock(project, {
    name: 'fixture_app',
    lockfileVersion: 3,
    packages: { '': { name: 'fixture_app' } },
  });
}

function writeLock(project: string, locked: unknown): void {
  writeFileSync(
    join(project, 'package-lock.json'),
    `${JSON.stringify(locked, null, 2)}\n`,
    'utf8',
  );
}
