import {
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

import { fakeHost, type FakeHost } from '../../test/doubles/watchHost.js';
import {
  WorkflowIRSchema,
  validateWorkflow,
  type WorkflowIR,
} from '../core/rules.js';
import type { Problem } from '../problem.js';
import type { StatusBar } from '../statusBar.js';
import {
  makeProject,
  readWorkflowFixture,
  writeWorkflow,
} from '../test-support/project.js';

import { generate, type CodegenResult } from './codegen.js';
import {
  LIB_GLOB,
  PROPOSAL_GLOB,
  WORKFLOW_GLOB,
  watchProjects,
  type Watchers,
} from './index.js';
import { scanProject } from './manifest.js';

/**
 * The loop between saving a workflow and having
 * code for it.
 *
 * Two halves, and they fail in different ways. The
 * generation itself is answerable against the
 * files on disk: the code is there, it carries the
 * header that says nobody may edit it, and what
 * the rules found about the document is reported
 * at the severity the rule fixed rather than at
 * whatever the reporting code felt like. The
 * wiring is answerable only by driving it — a
 * watcher registered on the wrong glob, or on a
 * folder nobody trusted, does nothing at all and
 * says nothing about it.
 */

const HEADER = '// GENERATED BY MBOSS — DO NOT EDIT.';

/** What the status bar was told, in order. */
type Reported = StatusBar & { finished: { ms: number; ok: boolean }[] };

function reporter(): Reported {
  const finished: { ms: number; ok: boolean }[] = [];

  return {
    finished,
    codegenFinished: (ms, ok) => void finished.push({ ms, ok }),
    codegenNeedsTrust: () => {},
    dispose: () => {},
  };
}

/**
 * Waits for something to become true rather than
 * for a length of time. Reading a project's
 * code-behind is real work and how long it takes is
 * not this spec's business.
 */
async function until(ready: () => boolean): Promise<void> {
  for (let tries = 0; tries < 600 && !ready(); tries += 1) {
    await new Promise((resolve) => setTimeout(resolve, 25));
  }

  expect(ready()).toBe(true);
}

/** Long enough for anything still in flight. Only
 *  used to assert that nothing more happens. */
async function quiet(): Promise<void> {
  await new Promise((resolve) => setTimeout(resolve, 200));
}

/** Every generated file, by project-relative
 *  path. */
function generatedFiles(project: string): string[] {
  const dir = join(project, 'src', 'workflows');

  return readdirSync(dir)
    .sort()
    .map((name) => `src/workflows/${name}`);
}

/** The problems reported against one file. */
function about(result: CodegenResult, path: string): Problem[] {
  return result.problems.filter((problem) => problem.file === path);
}

describe('generating from a document that compiles', () => {
  it('writes the code, with the header that says who owns it', async () => {
    const project = await makeProject({ lib: 'lib' });
    writeWorkflow(project, 'groom_booking');

    const result = await generate(project);

    const generated = readFileSync(
      join(project, 'src', 'workflows', 'groom_booking.workflow.ts'),
      'utf8',
    );

    expect(result.ok).toBe(true);
    expect(generated.split('\n')[0]).toBe(HEADER);
  });

  it('reports exactly what it put on disk', async () => {
    const project = await makeProject({ lib: 'lib' });
    writeWorkflow(project, 'groom_booking');

    const result = await generate(project);

    expect([...result.written].sort()).toEqual(generatedFiles(project));
  });

  it('says how long it took', async () => {
    const project = await makeProject({ lib: 'lib' });
    writeWorkflow(project, 'groom_booking');

    expect((await generate(project)).ms).toBeGreaterThanOrEqual(0);
  });
});

describe('what the rules found', () => {
  /**
   * Computed by asking the same function the canvas
   * and the compiler ask, rather than written out
   * here: a copy of core's wording in this file
   * would drift from core's wording without
   * anything failing.
   */
  it('is reported unchanged, against the document it is about', async () => {
    const project = await makeProject({ lib: 'lib' });
    const path = writeWorkflow(project, 'groom_booking');
    const ir = WorkflowIRSchema.parse(JSON.parse(readFileSync(path, 'utf8')));

    const result = await generate(project);
    const expected = validateWorkflow(ir, {
      manifest: scanProject(project).manifest,
    });

    expect(about(result, path)).toEqual(
      expected.map((found) => ({
        file: path,
        code: found.code,
        severity: found.severity,
        message: found.message,
      })),
    );
  });

  /**
   * The three rules about work not done yet report
   * as warnings, and every other rule as an error.
   * A pipeline that flattened them would turn every
   * half-drawn draft into a wall of red.
   */
  it('keeps a warning a warning and an error an error', async () => {
    const project = await makeProject({ lib: 'lib' });
    const path = writeMixed(project);

    const found = about(await generate(project), path);

    expect(found.filter((one) => one.severity === 'warning')).not.toHaveLength(
      0,
    );
    expect(found.filter((one) => one.severity === 'error')).not.toHaveLength(0);
  });

  it('names the rule, so a reader can look it up', async () => {
    const project = await makeProject();
    const path = writeWorkflow(project, 'empty_draft');

    expect(about(await generate(project), path)).toEqual([
      expect.objectContaining({ code: 'V01', severity: 'warning' }),
    ]);
  });
});

describe('a document that will not parse', () => {
  /**
   * The ordinary state of a file somebody is typing
   * into, and of one an agent is halfway through
   * writing. Throwing here would take the whole
   * project's generation down over one file.
   */
  it('is reported rather than thrown', async () => {
    const project = await makeProject({ lib: 'lib' });
    writeWorkflow(project, 'groom_booking');
    const broken = join(
      project,
      '.mboss',
      'workflows',
      'half_typed.workflow.json',
    );
    writeFileSync(broken, '{ "nodes": [', 'utf8');

    const result = await generate(project);

    expect(result.ok).toBe(false);
    expect(about(result, broken)).toHaveLength(1);
    expect(about(result, broken)[0]?.severity).toBe('error');
  });

  it('leaves the code that was already generated alone', async () => {
    const project = await makeProject({ lib: 'lib' });
    writeWorkflow(project, 'groom_booking');
    await generate(project);

    writeFileSync(
      join(project, '.mboss', 'workflows', 'half_typed.workflow.json'),
      '{ "nodes": [',
      'utf8',
    );
    await generate(project);

    expect(generatedFiles(project)).toContain(
      'src/workflows/groom_booking.workflow.ts',
    );
  });
});

describe('code-behind that does not compile', () => {
  it('is reported against the file that does not', async () => {
    const project = await makeProject({ lib: 'lib-broken' });
    writeWorkflow(project, 'empty_draft');

    const result = await generate(project);
    const path = join(project, 'lib', 'broken.ts');

    expect(about(result, path)).not.toHaveLength(0);
  });
});

describe('a compile that fails for a reason nobody chose', () => {
  /**
   * Not something a person could have typed — here,
   * a directory the compiler has to write into that
   * is not a directory. Reported all the same,
   * because a status bar that never updates and a
   * panel that never fills reads as the extension
   * having stopped working for no reason.
   */
  it('is reported rather than left silent', async () => {
    const project = await makeProject({ lib: 'lib' });
    writeWorkflow(project, 'groom_booking');

    rmSync(join(project, 'src'), { recursive: true });
    writeFileSync(join(project, 'src'), '', 'utf8');

    const result = await generate(project);

    expect(result.ok).toBe(false);
    expect(about(result, join(project, '.mboss'))).toEqual([
      expect.objectContaining({ severity: 'error' }),
    ]);
  });
});

describe('a project that is not one', () => {
  it('generates nothing and says nothing', async () => {
    const project = await makeProject();
    const result = await generate(join(project, 'not-a-project'));

    expect(result.ok).toBe(false);
    expect(result.written).toEqual([]);
  });
});

describe('the watchers', () => {
  it('watch the three things a project changes through', async () => {
    const { host } = await watching();

    expect(host.watching.map((one) => one.glob).sort()).toEqual(
      [LIB_GLOB, PROPOSAL_GLOB, WORKFLOW_GLOB].sort(),
    );
  });

  it('regenerate when a workflow document changes', async () => {
    const { project, host, status } = await watching({ lib: 'lib' });
    writeWorkflow(project, 'groom_booking');

    host.fire(WORKFLOW_GLOB, join(project, '.mboss', 'workflows', 'x.json'));

    await until(() => status.finished.length === 1);
    expect(generatedFiles(project)).toContain(
      'src/workflows/groom_booking.workflow.ts',
    );
  });

  it('regenerate when a document is saved in the editor', async () => {
    const { project, host, status } = await watching({ lib: 'lib' });
    writeWorkflow(project, 'groom_booking');

    host.save(
      join(project, '.mboss', 'workflows', 'groom_booking.workflow.json'),
    );

    await until(() => status.finished.length === 1);
    expect(generatedFiles(project)).toContain(
      'src/workflows/groom_booking.workflow.ts',
    );
  });

  it('ignore a save of a file that is not a workflow', async () => {
    const { project, host, status } = await watching({ lib: 'lib' });

    host.save(join(project, 'lib', 'notes.md'));

    await quiet();
    expect(status.finished).toHaveLength(0);
  });

  it('regenerate when the code-behind changes', async () => {
    const { project, host, status } = await watching({ lib: 'lib' });
    writeWorkflow(project, 'groom_booking');

    host.fire(LIB_GLOB, join(project, 'lib', 'findSlot.ts'));

    await until(() => status.finished.length === 1);
  });

  it('cost one generation for a burst of events', async () => {
    const { project, host, status } = await watching({ lib: 'lib' });
    writeWorkflow(project, 'groom_booking');
    const path = join(project, '.mboss', 'workflows', 'x.json');

    for (let event = 0; event < 5; event += 1) host.fire(WORKFLOW_GLOB, path);

    await until(() => status.finished.length === 1);
    await quiet();

    expect(status.finished).toHaveLength(1);
  });

  it('publish what they found where a person will see it', async () => {
    const { project, host } = await watching();
    const path = writeWorkflow(project, 'empty_draft');

    host.fire(WORKFLOW_GLOB, path);

    await until(() => host.published.length > 0);
    expect(host.published.at(-1)).toEqual([
      expect.objectContaining({ file: path, code: 'V01' }),
    ]);
  });

  it('tell the status bar what the generation cost', async () => {
    const { project, host, status } = await watching({ lib: 'lib' });
    writeWorkflow(project, 'groom_booking');

    host.fire(WORKFLOW_GLOB, join(project, '.mboss', 'workflows', 'x.json'));

    await until(() => status.finished.length === 1);
    expect(status.finished[0]?.ok).toBe(true);
    expect(status.finished[0]?.ms).toBeGreaterThanOrEqual(0);
  });

  it('notice a proposal arriving', async () => {
    const { project, host, watchers } = await watching();
    const seen: string[] = [];
    watchers.onProposal((path) => void seen.push(path));

    const path = join(project, '.mboss', 'proposals', 'p1.json');
    host.fire(PROPOSAL_GLOB, path);

    expect(seen).toEqual([path]);
  });

  it('let go of the PROBLEMS they published when disposed', async () => {
    const { host, watchers } = await watching();

    watchers.dispose();

    expect(host.disposed).toBe(true);
  });
});

describe('a folder nobody has trusted', () => {
  /**
   * Generating code writes TypeScript into the
   * folder, which is exactly what workspace trust
   * is a decision about. The canvas still draws and
   * still shows what the rules found; nothing runs
   * and nothing is written.
   */
  it('generates nothing', async () => {
    const { project, host, status } = await watching({
      lib: 'lib',
      trusted: false,
    });
    writeWorkflow(project, 'groom_booking');

    host.fire(WORKFLOW_GLOB, join(project, '.mboss', 'workflows', 'x.json'));

    await quiet();
    expect(status.finished).toHaveLength(0);
  });

  it('starts the moment it is trusted', async () => {
    const { project, host, status } = await watching({
      lib: 'lib',
      trusted: false,
    });
    writeWorkflow(project, 'groom_booking');

    host.trust();

    await until(() => status.finished.length === 1);
    expect(generatedFiles(project)).toContain(
      'src/workflows/groom_booking.workflow.ts',
    );
  });

  it('says on the status bar why nothing is happening', async () => {
    let asked = 0;
    const status: Reported = {
      ...reporter(),
      codegenNeedsTrust: () => void (asked += 1),
    };
    const project = await makeProject();
    const host = fakeHost({ folders: [project], trusted: false });

    watchProjects(host, status, { debounceMs: 5 }).dispose();

    expect(asked).toBe(1);
  });
});

describe('generating on demand', () => {
  it('does the work whatever the watchers were waiting for', async () => {
    const { project, watchers } = await watching({ lib: 'lib' });
    writeWorkflow(project, 'groom_booking');

    const run = await watchers.generateNow();

    expect(run).toMatchObject({ ran: true, ok: true, ms: expect.any(Number) });
    expect(generatedFiles(project)).toContain(
      'src/workflows/groom_booking.workflow.ts',
    );
  });

  /** Handed back as well as published, because the
   *  caller that asked for this generation may be
   *  the one that caused what it found. */
  it('hands back what it found', async () => {
    const { project, watchers } = await watching({ lib: 'lib-broken' });
    writeWorkflow(project, 'empty_draft');

    const run = await watchers.generateNow();

    expect(run.ran && run.problems).toContainEqual(
      expect.objectContaining({ file: join(project, 'lib', 'broken.ts') }),
    );
  });

  it('says it cannot when the folder is not trusted', async () => {
    const { watchers } = await watching({ trusted: false });

    expect(await watchers.generateNow()).toEqual({
      ran: false,
      reason: 'untrusted',
    });
  });

  it('says it cannot when no folder here is a project', async () => {
    const status = reporter();
    const host = fakeHost({ folders: ['/nowhere/at/all'] });
    const watchers = watchProjects(host, status, { debounceMs: 5 });

    expect(await watchers.generateNow()).toEqual({
      ran: false,
      reason: 'noProject',
    });

    watchers.dispose();
  });
});

/**
 * A watched project and the doubles it is watched
 * through. The window is short because these specs
 * wait on what happened, not on the clock.
 */
async function watching(opts?: {
  lib?: 'lib' | 'lib-broken';
  trusted?: boolean;
}): Promise<{
  project: string;
  host: FakeHost;
  status: Reported;
  watchers: Watchers;
}> {
  const project = await makeProject(
    opts?.lib === undefined ? undefined : { lib: opts.lib },
  );
  const host = fakeHost({ folders: [project], trusted: opts?.trusted ?? true });
  const status = reporter();
  const watchers = watchProjects(host, status, { debounceMs: 5 });

  return { project, host, status, watchers };
}

/**
 * A document with one of each severity: two blocks
 * wired with types that do not meet, and no trigger
 * to start any of it.
 */
function writeMixed(project: string): string {
  const document = JSON.parse(
    readWorkflowFixture('groom_booking'),
  ) as WorkflowIR;
  const ir = {
    ...document,
    name: 'mixed',
    title: 'Mixed',
    nodes: document.nodes.filter((node) =>
      ['parse_request', 'find_slot'].includes(node.id),
    ),
    edges: document.edges
      .filter((edge) => edge.id === 'e2')
      .map((edge) => ({ ...edge, type: 'WebhookEvent' })),
  };

  const path = join(project, '.mboss', 'workflows', 'mixed.workflow.json');

  mkdirSync(join(project, '.mboss', 'workflows'), { recursive: true });
  writeFileSync(path, `${JSON.stringify(ir, null, 2)}\n`, 'utf8');

  return path;
}
